### ISSUE TITLE
Error on Installation

### ISSUE THREAD

**Issue by FreshImmuc** [Impostor/Impostor#370]
# Bug Report

## Base Information
- Ubuntu 20.04
- Current
- Airship (2021.3.31)

## I confirm:
- [x] that I have searched for an existing bug report for this issue.

![image](https://user-images.githubusercontent.com/65733898/113217949-98a9e780-9276-11eb-9b18-e5a7e74a0e54.png)
This error happened. Idk how to fix it

**Comment by FreshImmuc** [comment]
Okay, So i installed it on Docker. Without docker compose. With normal Docker. The Console shows this:
![image](https://user-images.githubusercontent.com/65733898/113221694-7798c500-927d-11eb-8246-347c262eda4c.png)
Did everything work? Cause I got a Blackscreen when I tried to connect in Among US

**Comment by matiqo15** [comment]
First, you should use docker and docker-compose with sudo. Yest that from docker should work, but change you IP in config.json if you want to connect from other network

**Comment by JantsoP** [comment]
On the error you can see it's trying to mount /path/to/local/config.json.

On docker compose, it should look like this:

```
version: '3.4'

services:
  impostor:
    image: aeonlucid/impostor:nightly
    container_name: impostor
    ports:
      - 22023:22023/udp
    volumes:
      - /home/jantsop/susdedi/config.json:/app/config.json # For easy editing of the config
      - /home/jantsop/susdedi/plugins:/app/plugins         # Only needed if using plugins
      - /home/jantsop/susdedi/libraries:/app/libraries     # Only needed if using external libraries
```

Make sure that the config.json file exists already in your host machine in the directory specifie (mine is /home/jantsop/susdedi/config.json). It's something to do with docker that if no file exits, it will just create a folder. Idk why.

Sample config
```
{
  "Server": {
    "PublicIp": "127.0.0.1",
    "PublicPort": 22023,
    "ListenIp": "0.0.0.0",
    "ListenPort": 22023
  },
  "AntiCheat": {
    "Enabled": true,
    "BanIpFromGame": true
  }
}
```
